baseURL = "/"
title = "Rafael Tieppo"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "https-rafatieppo-github-io"
googleAnalytics = "UA-33432733-8"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"
  
[params.info]
description = "Agricultural Engineering, Emacs user, and improving as Data Scientist, works with Python and R"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Rafael Tieppo"
startYear = "2016"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu","social_menu","taxonomy_cloud"]
#sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
#footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[markup.goldmark.renderer]
unsafe= true

[params.social]
#codepen = "MunifTanjim"
email = "rafaeltieppo@yahoo.com.br"
#facebook = "MunifTanjim"
github = "rafatieppo"
#gitlab = "MunifTanjim"
#instagram = "MunifTanjim"
linkedin = "rafaeltieppo"
twitter = "rafatieppo"
#telegram = "MunifTanjim"
google_scholar = "ClN1Q6AAAAAJ"
#youtube = "UCT-U0rNerYxItGcuoPX-WYA"
researchgate = "rafael_tieppo"
orcid = "0000-0001-8132-4813"
stackoverflow= "3109019/rafa"


#[params.comments]
#enable = false
# 
## Isso: https://posativ.org/isso/
#[params.comments.isso]
#enable = false
#scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
#dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"
# 
#[params.comments.staticman]
#enable = true
#apiEndpoint = "https://api.staticman.net/v2/entry"
#maxDepth = 2
# 
#[params.comments.staticman.github]
#username = "MunifTanjim"
#repository = "minimo"
#branch = "master"
# 
## Utterances: https://utteranc.es
#[params.comments.utterances]
#enable = false
#issueTerm = "pathname" # pathname / url / title
# 
#[params.comments.utterances.github]
#username = "MunifTanjim"
#repository = "minimo"

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Home"
weight = -10
identifier = "hom"
url = "/"

[[menu.main]]
name = "Teaching"
weight = -9
identifier = "teachin"
url = "/teaching/"

[[menu.main]]
name = "Blog"
weight = -8
identifier = "post"
url = "/post/"

[[menu.main]]
name = "Portfolio"
weight = -7
identifier = "portfoli"
url = "/portfolio/"

[[menu.main]]
name = "About"
weight = -6
identifier = "about"
url = "/about/"


[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
